bot_token: 'TOKEN_GOES_HERE'

server_id: SERVER_ID_GOES_HERE

yes_words:
  - 'yah'
  - 'yas'
  - 'yes'
  - 'yeh'
  - 'yep'
  - 'ye'
  - 'yee'
  - 'yeah'
  - 'yup'
  - 'yurp'
  - 'totally'
  - 'totes'
  - 'you bet'
  - 'you know it'
  - 'sure'
  - 'for sure'
  - 'sure thing'
  - 'of course'
  - 'certainly'
  - 'definitely'
  - 'absolutely'
no_words:
  - 'no'
  - 'no thanks'
  - 'nah'
  - 'nay'
  - 'nope'
  - 'nop'
